stages:
  - test
  - deploy


test:
  image: python:latest
  stage: test
  before_script:
    - pip install -r requirements.txt
  when: on_success
  script:
    - python manage.py migrate
    - python manage.py collectstatic --noinput
  only:
    - main


deploy:
  image: ruby:latest
  stage: deploy
  before_script: 
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    - gem install dpl
    - dpl --provider=heroku --app=bankasugo --api-key=Heroku_Api_Key
  environment:
    name: main
    url: Heroku_App_Host
  only:
    - main