# Generated by Django 3.0.7 on 2022-04-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwallet',
            name='account_type',
            field=models.CharField(blank=True, choices=[('savings', 'savings'), ('current', 'current'), ('cheque', 'cheque')], max_length=100, null=True),
        ),
    ]
