# Generated by Django 3.0.7 on 2022-04-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_auto_20220413_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedeposits',
            name='bank_account_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='trans_form',
            field=models.CharField(choices=[('cash', 'cash'), ('cheque', 'cheque'), ('account_to_account', 'account_to_account')], max_length=20),
        ),
    ]
