# Generated by Django 3.0.7 on 2022-04-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_auto_20220315_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwallet',
            name='account_type',
            field=models.CharField(blank=True, choices=[('savings', 'savings'), ('current', 'current'), ('cheque', 'cheque')], max_length=100),
        ),
    ]
