# Generated by Django 3.0.7 on 2022-04-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_auto_20220405_2056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='history',
            new_name='Transaction',
        ),
    ]
